# Generated by Django 4.2.3 on 2026-05-27 10:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tests', '0002_usertestresult'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpeakingResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='speaking_audio/')),
                ('transcript', models.TextField(blank=True)),
                ('ai_feedback', models.TextField(blank=True)),
                ('band_score', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='speaking_results', to='tests.test')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='speaking_results', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
