# Generated by Django 4.2.3 on 2026-06-06 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0004_userprogress_dailyplan'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='audio_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
